configure: disable C++11 fallback

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -2024,16 +2024,6 @@ ICUDT_DIR="icu${ICU_BUNDLE_VERSION}/data"
 
 
 
-
-
-
-
-
-
-
-
-
-
 ##### OPTIONS #################################################################
 
 # shell variables/arguments accepted:
@@ -2325,30 +2315,8 @@ fi
 
 ### AUXILIARY FUNCTIONS ########################################################
 
-enable_cxx11() {
-    echo "*** Trying with C++11 compiler disabled."
-    force_cxx11="yes"
-    # unset cached C++ compiler features:
-    unset ac_cv_cxx_compiler_gnu
-    unset ac_cv_c_compiler_gnu
-    unset ac_cv_prog_cxx_g
-    unset ac_cv_prog_cc_g
-    unset ac_cv_prog_cc_c89
-    unset ac_cv_prog_CPP
-    unset ac_cv_prog_CXX
-    unset ac_cv_prog_CC
-    unset ac_cv_header_stdc
-    unset ac_cv_prog_ac_ct_CXX
-    unset ac_cv_prog_ac_ct_CC
-    unset ac_cv_cxx_namespaces
-    unset ac_cv_cxx_have_stl
-    unset ac_cv_objext
-    return 0
-}
-
-
-# Basic C++ compiler checks: are long long type and stl data structures
-# available? These are absolutely necessary to compile ICU>=55.
+# Basic C++ compiler checks: are long long type and the C++ standard library
+# data structures available? These are absolutely necessary to compile ICU>=55.
 #
 # If this is the case, return 0
 check_cpp() {
@@ -2357,6 +2325,9 @@ ac_cpp='$CXXCPP $CPPFLAGS'
 ac_compile='$CXX -c $CXXFLAGS $CPPFLAGS conftest.$ac_ext >&5'
 ac_link='$CXX -o conftest$ac_exeext $CXXFLAGS $CPPFLAGS $LDFLAGS conftest.$ac_ext $LIBS >&5'
 ac_compiler_gnu=$ac_cv_cxx_compiler_gnu
+
+
+    # AC_PROG_CXX  # we don't want to determine a C++ compiler to use as we rely on R CMD config
 
     ac_ext=cpp
 ac_cpp='$CXXCPP $CPPFLAGS'
@@ -2904,10 +2875,23 @@ ac_link='$CXX -o conftest$ac_exeext $CXXFLAGS $CPPFLAGS $LDFLAGS conftest.$ac_ex
 ac_compiler_gnu=$ac_cv_cxx_compiler_gnu
 
 
+cat confdefs.h - <<_ACEOF >conftest.$ac_ext
+/* end confdefs.h.  */
+
+            int main() { return 0; }
+
+
+_ACEOF
+if ac_fn_cxx_try_link "$LINENO"
+then :
+
+fi
+rm -f core conftest.err conftest.$ac_objext conftest.beam \
+    conftest$ac_exeext conftest.$ac_ext
+
     { printf '%s\n' "$as_me:${as_lineno-$LINENO}: checking whether the C++ compiler supports the 'long long' type" >&5
 printf %s "checking whether the C++ compiler supports the 'long long' type... " >&6; }
-
-cat confdefs.h - <<_ACEOF >conftest.$ac_ext
+    cat confdefs.h - <<_ACEOF >conftest.$ac_ext
 /* end confdefs.h.  */
 
         #include <iostream>
@@ -2940,116 +2924,6 @@ esac
 fi
 rm -f core conftest.err conftest.$ac_objext conftest.beam \
     conftest$ac_exeext conftest.$ac_ext
-
-    { printf '%s\n' "$as_me:${as_lineno-$LINENO}: checking whether the compiler implements namespaces" >&5
-printf %s "checking whether the compiler implements namespaces... " >&6; }
-if test ${ac_cv_cxx_namespaces+y}
-then :
-  printf %s "(cached) " >&6
-else case e in #(
-  e)
- ac_ext=cpp
-ac_cpp='$CXXCPP $CPPFLAGS'
-ac_compile='$CXX -c $CXXFLAGS $CPPFLAGS conftest.$ac_ext >&5'
-ac_link='$CXX -o conftest$ac_exeext $CXXFLAGS $CPPFLAGS $LDFLAGS conftest.$ac_ext $LIBS >&5'
-ac_compiler_gnu=$ac_cv_cxx_compiler_gnu
-
- cat confdefs.h - <<_ACEOF >conftest.$ac_ext
-/* end confdefs.h.  */
-namespace Outer { namespace Inner { int i = 0; }}
-int
-main (void)
-{
-using namespace Outer::Inner; return i;
-  ;
-  return 0;
-}
-_ACEOF
-if ac_fn_cxx_try_link "$LINENO"
-then :
-  ac_cv_cxx_namespaces=yes
-else case e in #(
-  e) ac_cv_cxx_namespaces=no ;;
-esac
-fi
-rm -f core conftest.err conftest.$ac_objext conftest.beam \
-    conftest$ac_exeext conftest.$ac_ext
- ac_ext=cpp
-ac_cpp='$CXXCPP $CPPFLAGS'
-ac_compile='$CXX -c $CXXFLAGS $CPPFLAGS conftest.$ac_ext >&5'
-ac_link='$CXX -o conftest$ac_exeext $CXXFLAGS $CPPFLAGS $LDFLAGS conftest.$ac_ext $LIBS >&5'
-ac_compiler_gnu=$ac_cv_cxx_compiler_gnu
-
- ;;
-esac
-fi
-{ printf '%s\n' "$as_me:${as_lineno-$LINENO}: result: $ac_cv_cxx_namespaces" >&5
-printf '%s\n' "$ac_cv_cxx_namespaces" >&6; }
-if test "$ac_cv_cxx_namespaces" = yes; then
-
-printf '%s\n' "#define HAVE_NAMESPACES /**/" >>confdefs.h
-
-fi
-
-{ printf '%s\n' "$as_me:${as_lineno-$LINENO}: checking whether the compiler supports the Standard Template Library" >&5
-printf %s "checking whether the compiler supports the Standard Template Library... " >&6; }
-if test ${ac_cv_cxx_have_stl+y}
-then :
-  printf %s "(cached) " >&6
-else case e in #(
-  e)
-
- ac_ext=cpp
-ac_cpp='$CXXCPP $CPPFLAGS'
-ac_compile='$CXX -c $CXXFLAGS $CPPFLAGS conftest.$ac_ext >&5'
-ac_link='$CXX -o conftest$ac_exeext $CXXFLAGS $CPPFLAGS $LDFLAGS conftest.$ac_ext $LIBS >&5'
-ac_compiler_gnu=$ac_cv_cxx_compiler_gnu
-
- cat confdefs.h - <<_ACEOF >conftest.$ac_ext
-/* end confdefs.h.  */
-#include <list>
-#include <deque>
-#ifdef HAVE_NAMESPACES
-using namespace std;
-#endif
-int
-main (void)
-{
-list<int> x; x.push_back(5);
-list<int>::iterator iter = x.begin(); if (iter != x.end()) ++iter; return 0;
-  ;
-  return 0;
-}
-_ACEOF
-if ac_fn_cxx_try_link "$LINENO"
-then :
-  ac_cv_cxx_have_stl=yes
-else case e in #(
-  e) ac_cv_cxx_have_stl=no ;;
-esac
-fi
-rm -f core conftest.err conftest.$ac_objext conftest.beam \
-    conftest$ac_exeext conftest.$ac_ext
- ac_ext=cpp
-ac_cpp='$CXXCPP $CPPFLAGS'
-ac_compile='$CXX -c $CXXFLAGS $CPPFLAGS conftest.$ac_ext >&5'
-ac_link='$CXX -o conftest$ac_exeext $CXXFLAGS $CPPFLAGS $LDFLAGS conftest.$ac_ext $LIBS >&5'
-ac_compiler_gnu=$ac_cv_cxx_compiler_gnu
-
- ;;
-esac
-fi
-{ printf '%s\n' "$as_me:${as_lineno-$LINENO}: result: $ac_cv_cxx_have_stl" >&5
-printf '%s\n' "$ac_cv_cxx_have_stl" >&6; }
-if test "$ac_cv_cxx_have_stl" = yes; then
-
-printf '%s\n' "#define HAVE_STL /**/" >>confdefs.h
-
-fi
-
-    if test "$ac_cv_cxx_have_stl" = not; then
-        return 1
-    fi
 
     { printf '%s\n' "$as_me:${as_lineno-$LINENO}: checking whether std::map is available" >&5
 printf %s "checking whether std::map is available... " >&6; }
@@ -3235,7 +3109,7 @@ else case e in #(
   e)
         { printf '%s\n' "$as_me:${as_lineno-$LINENO}: result: no" >&5
 printf '%s\n' "no" >&6; }
-        echo "*** This version of ICU4C cannot be used."
+        echo "*** The available ICU4C cannot be used."
         #echo "${MSG_CONFIG_FAIL}"
         return 1
      ;;
@@ -3269,7 +3143,7 @@ else case e in #(
   e)
         { printf '%s\n' "$as_me:${as_lineno-$LINENO}: result: no" >&5
 printf '%s\n' "no" >&6; }
-        echo "*** This version of ICU4C cannot be used."
+        echo "*** The available ICU4C cannot be used."
         #echo "${MSG_CONFIG_FAIL}"
         return 1
      ;;
@@ -3454,10 +3328,10 @@ check_flags_icu_bundle() {
     ICU_LDFLAGS=""
     ICU_LIBS=""
 
-    CXXFLAGS="${with_extra_cxxflags} ${R_CXXPICFLAGS} ${R_CXXFLAGS}"
-    CPPFLAGS="${with_extra_cppflags} ${ICU_CPPFLAGS} ${R_CPPFLAGS} -UUCONFIG_USE_LOCAL"  # don't use uconfig_local yet
-    LDFLAGS="${with_extra_ldflags} ${ICU_LDFLAGS} ${R_LDFLAGS}"
-    LIBS="${with_extra_libs} ${ICU_LIBS} ${R_LIBS}"
+    CXXFLAGS="${R_CXXPICFLAGS} ${R_CXXFLAGS} ${with_extra_cxxflags}"
+    CPPFLAGS="${ICU_CPPFLAGS} ${R_CPPFLAGS} ${with_extra_cppflags} -UUCONFIG_USE_LOCAL"  # don't use uconfig_local yet
+    LDFLAGS="${ICU_LDFLAGS} ${R_LDFLAGS} ${with_extra_ldflags}"
+    LIBS="${ICU_LIBS} ${R_LIBS} ${with_extra_libs}"
 
     # NOTE: One way for dealing with the *Compiler or options invalid for pre-UNIX 03
     # X/Open applications and pre-2001 POSIX applications* error on Solaris
@@ -3541,7 +3415,7 @@ else case e in #(
             { printf '%s\n' "$as_me:${as_lineno-$LINENO}: result: no" >&5
 printf '%s\n' "no" >&6; }
 
-            CPPFLAGS="${with_extra_cppflags} -DSTRINGI_MAX_ALIGN_T_STD ${ICU_CPPFLAGS} ${R_CPPFLAGS} -UUCONFIG_USE_LOCAL"
+            CPPFLAGS="-DSTRINGI_MAX_ALIGN_T_STD ${ICU_CPPFLAGS} ${R_CPPFLAGS} ${with_extra_cppflags} -UUCONFIG_USE_LOCAL"
             { printf '%s\n' "$as_me:${as_lineno-$LINENO}: checking whether alignof(::max_align_t) is available" >&5
 printf %s "checking whether alignof(::max_align_t) is available... " >&6; }
             cat confdefs.h - <<_ACEOF >conftest.$ac_ext
@@ -3599,113 +3473,23 @@ rm -f core conftest.err conftest.$ac_objext conftest.beam \
 
 ################################################################################
 
-force_cxx11="no"  # start by using the default 'CXX' compiler
+STRINGI_CXXSTD=""
+R_CXXFLAGS=`"${R_PATH}" CMD config CXXFLAGS`
+R_CPPFLAGS=`"${R_PATH}" CMD config CPPFLAGS`
+R_CXXPICFLAGS=`"${R_PATH}" CMD config CXXPICFLAGS`
+R_LDFLAGS=
+R_LIBS=
+CXX=`"${R_PATH}" CMD config CXX`
+LD=`"${R_PATH}" CMD config SHLIB_CXXLD`
+CXXFLAGS="${R_CXXFLAGS} ${with_extra_cxxflags}"
+CPPFLAGS="${R_CPPFLAGS} ${with_extra_cppflags}"
+LDFLAGS="${R_LDFLAGS} ${with_extra_ldflags}"
+LIBS="${R_LIBS} ${with_extra_libs}"
 
-while true; do
-    # Step 1.  force_cxx11="no"
-    # Step 2.  force_cxx11="yes"
-    # Step 3.  Fail.
-
-    LD=`"${R_PATH}" CMD config SHLIB_CXXLD`
-
-    R_CPPFLAGS=`"${R_PATH}" CMD config CPPFLAGS`
-    R_LIBS=
-    R_LDFLAGS=
-
-
-    if test $force_cxx11 = "no"; then
-        STRINGI_CXXSTD=""
-
-        CXX=`"${R_PATH}" CMD config CXX`
-
-        R_CXXFLAGS=`"${R_PATH}" CMD config CXXFLAGS`
-        R_CXXPICFLAGS=`"${R_PATH}" CMD config CXXPICFLAGS`
-    else
-        STRINGI_CXXSTD="CXX_STD=CXX11"
-
-        CXX_tmp1=`"${R_PATH}" CMD config CXX11`
-        CXX_tmp2=`"${R_PATH}" CMD config CXX11STD`
-        CXX="${CXX_tmp1} ${CXX_tmp2}"
-
-        R_CXXFLAGS=`"${R_PATH}" CMD config CXX11FLAGS`
-        R_CXXPICFLAGS=`"${R_PATH}" CMD config CXX11PICFLAGS`
-    fi
-
-
-    CXXFLAGS="${with_extra_cxxflags} ${R_CXXFLAGS}"
-    CPPFLAGS="${with_extra_cppflags} ${R_CPPFLAGS}"
-    LDFLAGS="${with_extra_ldflags} ${R_LDFLAGS}"
-    LIBS="${with_extra_libs} ${R_LIBS}"
-
-    if ! check_cpp; then
-        if test $force_cxx11 = "no"; then
-            enable_cxx11
-            continue
-        else
-            echo "${MSG_CONFIG_FAIL}"
-            exit 1
-        fi
-    fi
-
-    ##### CHECK FOR ICU4C ##########################################################
-
-    ICU_FOUND=0
-    if test $enable_pkg_config = "no"; then
-        # Use of pkg-config disabled, nothing to do
-        echo "*** System ICU4C has been disabled."
-    else
-        if ! detect_icu_with_pkg_config; then
-            echo "*** Trying with 'standard' fallback flags"
-            # (#238, #220) trying "standard" fallback flags
-            ICU_CPPFLAGS=""
-            ICU_LDFLAGS=""
-            ICU_LIBS="-licui18n -licuuc -licudata"
-        fi
-        if check_icu_with_pkg_config; then
-            ICU_FOUND=1  # success
-        fi
-    fi
-
-
-    if test $ICU_FOUND = 1; then
-        break  # all set!
-    fi
-
-    if test $enable_icu_bundle = "no"; then
-        echo "*** *********************************************************************"
-        echo "*** Failed to configure 'stringi' with the enforced use of the system ICU"
-        echo "*** Consider installing, e.g., libicu-devel (RHEL, Fedora)"
-        echo "*** or libicu-dev (Debian, Ubuntu) along with 'pkg-config'"
-        if test $force_cxx11 = "no"; then
-            enable_cxx11
-            continue
-        else
-            echo "${MSG_CONFIG_FAIL}"
-            exit 1
-        fi
-    fi
-
-    echo "*** Using the ICU ${ICU_BUNDLE_VERSION} bundle that comes with 'stringi'."
-
-    ICU_BUNDLE_OK=0
-    if check_flags_icu_bundle; then
-        ICU_BUNDLE_OK=1  # success
-    fi
-
-    if test $ICU_BUNDLE_OK = 1; then
-        break  # all set!
-    fi
-
-    echo "*** Failed to configure package build with the ICU bundle usage."
-    if test $force_cxx11 = "no"; then
-        enable_cxx11
-        continue
-    else
-        echo "${MSG_CONFIG_FAIL}"
-        exit 1
-    fi
-
-done # end while
+if ! check_cpp; then
+    echo "${MSG_CONFIG_FAIL}"
+    exit 1
+fi
 
 
 ac_header= ac_cache=
@@ -3747,10 +3531,45 @@ fi
 
 
 
-###### DOWNLOAD ICUDT (IF NEEDED) ##############################################
+##### CHECK FOR ICU4C ##########################################################
+
+ICU_FOUND=0
+if test $enable_pkg_config = "no"; then
+    # Use of pkg-config disabled, nothing to do
+    echo "*** System ICU4C has been disabled."
+else
+    if ! detect_icu_with_pkg_config; then
+        echo "*** Trying 'standard' fallback flags"
+        # (#238, #220) trying "standard" fallback flags
+        ICU_CPPFLAGS=""
+        ICU_LDFLAGS=""
+        ICU_LIBS="-licui18n -licuuc -licudata"
+    fi
+    if check_icu_with_pkg_config; then
+        ICU_FOUND=1  # success
+    fi
+fi
 
 if test $ICU_FOUND = 0; then
-    # There are systems with no internet access
+
+    if test $enable_icu_bundle = "no"; then
+        echo "*** *********************************************************************"
+        echo "*** Failed to configure 'stringi' with the enforced use of the system ICU"
+        echo "*** Consider installing, e.g., libicu-devel (RHEL, Fedora)"
+        echo "*** or libicu-dev (Debian, Ubuntu) along with 'pkg-config'"
+        echo "${MSG_CONFIG_FAIL}"
+        exit 1
+    fi
+
+    echo "*** Using the ICU ${ICU_BUNDLE_VERSION} bundle that comes with 'stringi'."
+
+    if ! check_flags_icu_bundle; then
+        echo "${MSG_CONFIG_FAIL}"
+        exit 1
+    fi
+
+
+    # There are systems with no internet access - Download icudt if needed
     { printf '%s\n' "$as_me:${as_lineno-$LINENO}: checking whether the ICU data library is available" >&5
 printf %s "checking whether the ICU data library is available... " >&6; }
     "${R_PATH}" --vanilla -s -e "setwd(\"src/\"); \
@@ -3765,7 +3584,11 @@ printf %s "checking whether the ICU data library is available... " >&6; }
         echo "*** *********************************************************************"
         exit 1
     fi
+
 fi
+
+
+
 
 
 ##### PREPARE SOURCE FILES LISTS ###############################################
@@ -3806,10 +3629,10 @@ else
     STRINGI_OBJECTS="\$(STRI_OBJECTS)"
 fi
 
-STRINGI_CXXFLAGS="${with_extra_cxxflags} ${R_CXXPICFLAGS}"
-STRINGI_CPPFLAGS="-I. ${with_extra_cppflags} ${ICU_CPPFLAGS}"
-STRINGI_LDFLAGS="${with_extra_ldflags} ${ICU_LDFLAGS}"
-STRINGI_LIBS="${with_extra_libs} ${ICU_LIBS}"
+STRINGI_CXXFLAGS="${R_CXXPICFLAGS} ${with_extra_cxxflags}"
+STRINGI_CPPFLAGS="-I. ${ICU_CPPFLAGS} ${with_extra_cppflags}"
+STRINGI_LDFLAGS="${ICU_LDFLAGS} ${with_extra_ldflags}"
+STRINGI_LIBS="${ICU_LIBS} ${with_extra_libs}"
 
 DISABLE_RESOLVE_LOCALE_NAME=1  # this does not apply on non-Windows platforms
 
