#176 ongoing
Former-commit-id: 13c0abee589ac2e82d00ad2d01b3d8f3dd252950

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -4463,6 +4463,57 @@ rm -f core conftest.err conftest.$ac_objext conftest.$ac_ext
 fi
 rm -f core conftest.err conftest.$ac_objext conftest.$ac_ext
 
+   ac_ext=cpp
+ac_cpp='$CXXCPP $CPPFLAGS'
+ac_compile='$CXX -c $CXXFLAGS $CPPFLAGS conftest.$ac_ext >&5'
+ac_link='$CXX -o conftest$ac_exeext $CXXFLAGS $CPPFLAGS $LDFLAGS conftest.$ac_ext $LIBS >&5'
+ac_compiler_gnu=$ac_cv_cxx_compiler_gnu
+
+   { $as_echo "$as_me:${as_lineno-$LINENO}: checking whether we may compile src/icu55/common/putil.cpp" >&5
+$as_echo_n "checking whether we may compile src/icu55/common/putil.cpp... " >&6; }
+   cat confdefs.h - <<_ACEOF >conftest.$ac_ext
+/* end confdefs.h.  */
+
+      `${CAT} src/icu55/common/putil.cpp`
+
+_ACEOF
+if ac_fn_cxx_try_compile "$LINENO"; then :
+
+      { $as_echo "$as_me:${as_lineno-$LINENO}: result: yes" >&5
+$as_echo "yes" >&6; }
+
+else
+
+      { $as_echo "$as_me:${as_lineno-$LINENO}: result: no" >&5
+$as_echo "no" >&6; }
+      with_extra_cxxflags="${with_extra_cXXflags} -D_XPG6"
+      CXXFLAGS="${CXXFLAGS} -D_XPG6"
+      { $as_echo "$as_me:${as_lineno-$LINENO}: checking whether we may compile src/icu55/common/putil.cpp with -D_XPG6" >&5
+$as_echo_n "checking whether we may compile src/icu55/common/putil.cpp with -D_XPG6... " >&6; }
+      cat confdefs.h - <<_ACEOF >conftest.$ac_ext
+/* end confdefs.h.  */
+
+         `${CAT} src/icu55/common/putil.cpp`
+
+_ACEOF
+if ac_fn_cxx_try_compile "$LINENO"; then :
+
+         { $as_echo "$as_me:${as_lineno-$LINENO}: result: yes" >&5
+$as_echo "yes" >&6; }
+
+else
+
+         { $as_echo "$as_me:${as_lineno-$LINENO}: result: no" >&5
+$as_echo "no" >&6; }
+         echo "*** The ICU bundle cannot be build. Upgrade your compiler flags."
+         exit 1
+
+fi
+rm -f core conftest.err conftest.$ac_objext conftest.$ac_ext
+
+fi
+rm -f core conftest.err conftest.$ac_objext conftest.$ac_ext
+
    return 0
 }
 
