#220: notify more explicitly about missing pkg-config
Former-commit-id: cc44c8da0df3da944ced8a36d29d14d7e2099670

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -633,7 +633,6 @@ STRINGI_ICU_I18N_SOURCES_CPP
 STRINGI_ICU_COMMON_SOURCES_C
 STRINGI_ICU_COMMON_SOURCES_CPP
 STRINGI_SOURCES_CPP
-PKG_CONFIG
 ac_ct_CXX
 EGREP
 GREP
@@ -656,9 +655,10 @@ CPPFLAGS
 CPP
 CFLAGS
 CC
-CAT
 PKG_CONFIG_PATH
 ICUDT_DIR
+PKG_CONFIG
+CAT
 R_HOME
 target_alias
 host_alias
@@ -716,9 +716,10 @@ with_extra_libs
 host_alias
 target_alias
 R_HOME
+CAT
+PKG_CONFIG
 ICUDT_DIR
 PKG_CONFIG_PATH
-CAT
 CC
 CFLAGS
 CPP
@@ -1379,6 +1380,10 @@ Some influential environment variables:
   R_HOME      Override the default directory with R installation, e.g.,
               /usr/lib64/R, where /usr/lib64 is in the search path. Note that
               $R_HOME/bin/R should point to the R executable.
+  CAT         The 'cat' command used for generating the list of source files
+              to compile.
+  PKG_CONFIG  The 'pkg-config' command used for getting necessary compiler
+              flags to link to and existing libicu installation.
   ICUDT_DIR   Optional directory from which an already downloaded ICU data
               archive (icudt*.zip) may be copied; either an absolute path or a
               path relative to <package source dir>/src; defaults to
@@ -1386,8 +1391,6 @@ Some influential environment variables:
   PKG_CONFIG_PATH
               An optional list of directories to search for pkg-config's .pc
               files.
-  CAT         The 'cat' command used for generating the list of source files
-              to compile.
   CC          Purposedly ignored.
   CFLAGS      Purposedly ignored.
   CPP         Purposedly ignored.
@@ -2177,6 +2180,8 @@ ICU_VERSION_NEEDED="50" # minimal version of ICU4C required to build stringi
 
 # shell variables/arguments accepted:
 # R_HOME - R's home dir
+
+
 
 
 
@@ -4220,8 +4225,7 @@ fi
  # auto-detect
 
    if test ! -f "${PKG_CONFIG}"; then
-      echo "*** The pkg-config script could not be found"
-      echo "*** Make sure it is installed if you want to use system ICU4C-devel installation"
+      echo "*** pkg-config could not be found"
       return 1 # go back immediately
    fi
 
@@ -4232,8 +4236,7 @@ $as_echo_n "checking with pkg-config for ICU4C installed... " >&6; }
       # pkg config doesn't know about icu-i18n
       { $as_echo "$as_me:${as_lineno-$LINENO}: result: no" >&5
 $as_echo "no" >&6; }
-      echo "*** The pkg-config script did not detect ICU4C-devel libraries installed"
-      echo "*** We will build ICU4C from sources"
+      echo "*** pkg-config did not detect ICU4C-devel libraries installed"
       return 1 # nothing more to do
    fi
 
@@ -4252,7 +4255,6 @@ $as_echo_n "checking for ICU4C >= $ICU_VERSION_NEEDED... " >&6; }
 $as_echo "no" >&6; }
       echo "*** ICU4C ${ICU_VERSION} has been detected"
       echo "*** Minimal requirements, i.e. ICU4C >= ${ICU_VERSION_NEEDED}, are not met"
-      echo "*** We will build ICU4C from sources"
       return 1 # you may quit querying pkg-config here
    fi
    { $as_echo "$as_me:${as_lineno-$LINENO}: result: yes" >&5
@@ -4313,7 +4315,7 @@ else
 
       { $as_echo "$as_me:${as_lineno-$LINENO}: result: no" >&5
 $as_echo "no" >&6; }
-      echo "*** ICU4C will be built from sources"
+      echo "*** System ICU4C cannot be used"
       return 1
 
 fi
@@ -4601,6 +4603,13 @@ rm -f core conftest.err conftest.$ac_objext conftest.$ac_ext
 }
 
 if test $ICU_FOUND = 0; then
+   if test $enable_icu_bundle = "no"; then
+      echo "*** Failed to configure package build with forced system ICU usage"
+      echo "*** Consider installing, e.g., libicu-devel (RHEL, Fedora) or libicu-dev (Debian, Ubuntu)"
+      echo "*** together with pkg-config"
+      exit 1
+   fi
+
    OLD_CFLAGS=$CFLAGS
    OLD_CXXFLAGS=$CXXFLAGS
    OLD_CPPFLAGS=$CPPFLAGS
@@ -4651,7 +4660,8 @@ STRINGI_ICU_STUBDATA_SOURCES_C=`${CAT} src/icu55_stubdata_c.txt`
 if test $ICU_FOUND = 0; then
    if test $enable_icu_bundle = "no"; then
       echo "*** Failed to configure package build with forced system ICU usage"
-      echo "*** Make sure that libicu-dev is properly installed"
+      echo "*** Consider installing, e.g., libicu-devel (RHEL, Fedora) or libicu-dev (Debian, Ubuntu)"
+      echo "*** together with pkg-config"
       exit 1
    fi
 
