fix #296

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -4229,7 +4229,7 @@ rm -f core conftest.err conftest.$ac_objext \
          disable_cxx11
          continue
       else
-         echo "*** stringi cannot be build. Check your compiler flags (Makeconf, Makevars, etc.)."
+         echo "*** stringi cannot be built. Check your compiler flags (Makeconf, Makevars, etc.)."
          echo "*** also, verify your C++ compiler's abilities (long long, STL, etc. support)"
          exit 1
       fi
@@ -4671,7 +4671,7 @@ rm -f core conftest.err conftest.$ac_objext \
    # file is copyrighted, so we have to cope with this error in another way:
    # adding -D_XPG6 flag conditionally.
 
-      if test ${ICU_BUNDLE_VERSION} = 55; then
+      if test ${ICU_BUNDLE_VERSION} -le 60; then
          # ICU 61 doesn't provide any .c files anymore
          ac_ext=c
 ac_cpp='$CPP $CPPFLAGS'
@@ -4715,12 +4715,12 @@ else
 
                { $as_echo "$as_me:${as_lineno-$LINENO}: result: no" >&5
 $as_echo "no" >&6; }
-               echo "*** The ICU bundle cannot be build. Upgrade your compiler flags."
+               echo "*** The ICU bundle cannot be built. Upgrade your compiler flags."
                if test "x$enable_cxx11" == "xyes"; then
                   disable_cxx11
                   continue
                else
-                  echo "*** stringi cannot be build. Check your compiler flags (Makeconf, Makevars, etc.)."
+                  echo "*** stringi cannot be built. Check your compiler flags (Makeconf, Makevars, etc.)."
                   exit 1
                fi
 
@@ -4773,12 +4773,12 @@ else
 
             { $as_echo "$as_me:${as_lineno-$LINENO}: result: no" >&5
 $as_echo "no" >&6; }
-            echo "*** The ICU4C bundle could not be build. Upgrade your compiler flags."
+            echo "*** The ICU4C bundle could not be built. Upgrade your compiler flags."
             if test "x$enable_cxx11" == "xyes"; then
                disable_cxx11
                continue
             else
-               echo "*** stringi cannot be build. Check your compiler flags (Makeconf, Makevars, etc.)."
+               echo "*** stringi cannot be built. Check your compiler flags (Makeconf, Makevars, etc.)."
                exit 1
             fi
 
@@ -4787,6 +4787,65 @@ rm -f core conftest.err conftest.$ac_objext conftest.$ac_ext
 
 fi
 rm -f core conftest.err conftest.$ac_objext conftest.$ac_ext
+
+      if test ${ICU_BUNDLE_VERSION} -gt 60; then
+         ac_ext=cpp
+ac_cpp='$CXXCPP $CPPFLAGS'
+ac_compile='$CXX -c $CXXFLAGS $CPPFLAGS conftest.$ac_ext >&5'
+ac_link='$CXX -o conftest$ac_exeext $CXXFLAGS $CPPFLAGS $LDFLAGS conftest.$ac_ext $LIBS >&5'
+ac_compiler_gnu=$ac_cv_cxx_compiler_gnu
+
+         { $as_echo "$as_me:${as_lineno-$LINENO}: checking whether we may compile src/icu${ICU_BUNDLE_VERSION}/i18n/number_affixutils.cpp" >&5
+$as_echo_n "checking whether we may compile src/icu${ICU_BUNDLE_VERSION}/i18n/number_affixutils.cpp... " >&6; }
+         cat confdefs.h - <<_ACEOF >conftest.$ac_ext
+/* end confdefs.h.  */
+
+             `${CAT} src/icu${ICU_BUNDLE_VERSION}/i18n/number_affixutils.cpp`
+
+_ACEOF
+if ac_fn_cxx_try_compile "$LINENO"; then :
+
+             { $as_echo "$as_me:${as_lineno-$LINENO}: result: yes" >&5
+$as_echo "yes" >&6; }
+
+else
+
+             { $as_echo "$as_me:${as_lineno-$LINENO}: result: no" >&5
+$as_echo "no" >&6; }
+             with_extra_cxxflags="${with_extra_cxxflags} -D_XPG6"
+             CXXFLAGS="${CXXFLAGS} -D_XPG6"
+             { $as_echo "$as_me:${as_lineno-$LINENO}: checking whether we may compile src/icu${ICU_BUNDLE_VERSION}/i18n/number_affixutils.cpp with -D_XPG6" >&5
+$as_echo_n "checking whether we may compile src/icu${ICU_BUNDLE_VERSION}/i18n/number_affixutils.cpp with -D_XPG6... " >&6; }
+             cat confdefs.h - <<_ACEOF >conftest.$ac_ext
+/* end confdefs.h.  */
+
+                 `${CAT} src/icu${ICU_BUNDLE_VERSION}/i18n/number_affixutils.cpp`
+
+_ACEOF
+if ac_fn_cxx_try_compile "$LINENO"; then :
+
+                 { $as_echo "$as_me:${as_lineno-$LINENO}: result: yes" >&5
+$as_echo "yes" >&6; }
+
+else
+
+                 { $as_echo "$as_me:${as_lineno-$LINENO}: result: no" >&5
+$as_echo "no" >&6; }
+                 echo "*** The ICU4C bundle could not be built. Upgrade your compiler flags."
+                 if test "x$enable_cxx11" == "xyes"; then
+                 disable_cxx11
+                 continue
+                 else
+                 echo "*** stringi cannot be built. Check your compiler flags (Makeconf, Makevars, etc.)."
+                 exit 1
+                 fi
+
+fi
+rm -f core conftest.err conftest.$ac_objext conftest.$ac_ext
+
+fi
+rm -f core conftest.err conftest.$ac_objext conftest.$ac_ext
+      fi
 
       return 0
    }
@@ -4800,7 +4859,7 @@ rm -f core conftest.err conftest.$ac_objext conftest.$ac_ext
             disable_cxx11
             continue
          else
-            echo "*** stringi cannot be build. Check your compiler flags (Makeconf, Makevars, etc.)."
+            echo "*** stringi cannot be built. Check your compiler flags (Makeconf, Makevars, etc.)."
             exit 1
          fi
       fi
